[workspace]
members = [
    "crates/quickbridge",
    "crates/quickbridge-core",
    "crates/quickbridge-runtime",
    "crates/quickbridge-ui",
]
resolver = "3"

[workspace.package]
version = "0.2.0"
edition = "2024"
rust-version = "1.94"
license = "MIT"
repository = "https://github.com/DG02002/quickbridge"
homepage = "https://github.com/DG02002/quickbridge"
documentation = ""

[workspace.dependencies]
anyhow = "1.0.103"
assert_cmd = "2.2.2"
axum = "0.8.9"
clap = { version = "4.6.1", features = ["derive", "wrap_help"] }
crossterm = { version = "0.29.0", features = ["event-stream"] }
futures-util = "0.3.32"
insta = "1.48.0"
predicates = "3.1.4"
ratatui = "0.30.2"
reqwest = { version = "0.13.4", default-features = false, features = ["rustls", "http2"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
tempfile = "3.27.0"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["full"] }
tokio-util = { version = "0.7.18", features = ["io"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "fmt"] }
vt100 = "0.16.2"

[workspace.lints.rust]
future-incompatible = "warn"
nonstandard-style = "warn"

[workspace.lints.clippy]
await_holding_lock = "deny"
large_enum_variant = "deny"
needless_question_mark = "deny"
redundant_clone = "deny"
